project:
  type: website
  output-dir: _site

website:
  title: "Thiago Gonçalves-Souza"
  site-url: "https://thiago-goncalves-souza.github.io"
  navbar:
    logo: images/profile.jpg
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Supervisions
        href: supervisions.qmd
      - text: CV
        href: cv.qmd
      - text: Contact
        href: contact.qmd
  page-footer:
    left: |
      © {{< 2025 >}} Thiago Gonçalves-Souza • <a href="mailto:tgoncalv@umich.edu">tgoncalv@umich.edu</a>
    right: |
      <a href="https://orcid.org/0000-0001-8471-7479">ORCID</a> • <a href="https://scholar.google.com.br/citations?hl=en&user=TjaP2l8AAAAJ&view_op=list_works&sortby=pubdate">Google Scholar</a>
  favicon: images/profile.jpg
  open-graph: true
  twitter-card: true
  repo-url: https://github.com/thiago-goncalves-souza/thiago-goncalves-souza.github.io
  repo-actions: [source, issue]

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toggle: true
    css: styles.css         
    toc: true
    smooth-scroll: true
    code-copy: true
    link-external-newwindow: true

date-format: long
lang: en
