---
title: "Supervisions"
---

## Exchange Graduate Students

- **Luh S. Santos**, PhD — University of Michigan (co-advised with [Marjorie Weber](https://lsa.umich.edu/eeb/people/faculty/marjorie-weber.html))
- **Gabriel Xavier Boldorini Ariero**, PhD — University of Michigan (co-advised with [Peter Reich](https://seas.umich.edu/research/faculty/peter-reich))
- **Alexandre P. Neto**, PhD — University of Michigan (co-advised with [Fernando Rodrigues](https://scholar.google.com/citations?user=8bXxpqYAAAAJ&hl=en) and [Nate Sanders](https://lsa.umich.edu/eeb/people/faculty/njsander.html))  
---

## Current Graduate Students and Postdocs

- **Dunya Diyadawagamage**, MS — SEAS, University of Michigan  
- **Ingrid da Silva Lima**, PhD — Federal Rural University of Pernambuco, Brazil  
- **Gabriela Albuquerque Galvão**, PhD — Federal Rural University of Pernambuco, Brazil  
- **Gabriel Xavier Boldorini Ariero**, PhD — Federal Rural University of Pernambuco, Brazil  
- **Tamilie Carvalho**, Postdoc, IGCB, University of Michigan (co-supervised with [Tim James](https://lsa.umich.edu/eeb/people/faculty/tyjames.html) and [Meghan Duffy](https://lsa.umich.edu/eeb/people/faculty/duffymeg.html)). [You can see Tami's papers here](https://scholar.google.com/citations?user=oES2VtYAAAAJ&hl=pt-BR)

---

## Previous Postdoctoral Researchers

- **Leonardo da Silva Chaves** (2021)  
- **Rodrigo F.R. Carmo** (2022)  

---

## Previous Graduate Students

- **Aparecida Barbosa de Paiva**, PhD (2025)  
- **Aníbal da Silva Cantalice**, PhD (2025)  
- **Victor Leandro-Silva**, PhD (2025)  
- **Mirela Natália Santos**, PhD (2024)  
- **Reginaldo Augusto Gusmão**, PhD (2024)  
- **Arthur Ramalho Magalhães**, PhD (2023)  
- **Ingrid da Silva Lima**, MS (2023)  
- **Gabriela Albuquerque Galvão**, MS (2023)  
- **Gabriel Xavier Boldorini Ariero**, MS (2023)  
- **Pedro Albuquerque Sena**, PhD (2021)  
- **Paulo Sérgio Monteiro**, PhD (2021)  
- **Paulo Mateus Martins Sobrinho**, PhD (2021)  
- **Victor Leandro-Silva**, MS (2021)  
- **Cássio Henrique C. da Silva**, MS (2020)  
- **Theo Branco O. Wanderley**, MS (2020)  
- **Reginaldo Augusto Gusmão**, MS (2019)  
- **Tiago Nascimento Bernabé**, PhD (2019)  
- **Lilian Sayuri Ouchi Melo**, PhD (2018)  
- **Gisiane Rodrigues de Lima**, MS (2018)  
- **Pedro Albuquerque Sena**, MS (2017)  
- **Paulo Gusmão**, MS (2017)  

---

## Previous Undergraduate Honor Thesis Students

- **Stephanie Santana Silva**  
- **Camila Chagas Patriota**  
- **Gabriel Xavier Boldorini Ariero**  
- **Gabriela Albuquerque Galvão**  
- **Gustavo Henrique Aires**  
- **Theo Branco O. Wanderley**  
- **Cássio Henrique C. da Silva**  
- **Gabrielle Firmino Soares**  
